### ISSUE TITLE
Server crashes if code returns with an error. 

### ISSUE THREAD

**Issue by IvanFon** [LisgarComputingClub/Online-Judge#9]

**Comment by spencereir** [comment]
There's a `result.compilemessage` property that we could check for. Naturally can't wait for stuff like Ruby sending compile messages even on successful compile though >_<

Anyway the JSON from HackerRank should give us enough info to solve this easily

**Comment by IvanFon** [comment]
The HackerRank API docs are [here](https://www.hackerrank.com/api/docs) and the docs for the Node.js library are [here](http://node-machine.org/machinepack-hackerrank). None of them are very descriptive. Maybe we should try going through each language and storing the JSON for bad code so we can find the best way to find and output errors.

**Comment by IvanFon** [comment]
Fixed with commit [8b1a2d6](https://github.com/LisgarComputingClub/Online-Judge/commit/8b1a2d60d20582668271b8404692bba0301845be).
